version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  simple:
    format: "%(asctime)s:%(levelname)s:%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s:%(module)s:%(funcName)s:%(name)s:%(levelname)s:%(message)s"
filters:
  console_filter:
    "()": "__main__.FilterLogs"
handlers:
  default:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: ERROR
    formatter: standard
    filters: [console_filter]
  file_handler:
    class: logging.FileHandler
    filename: "./logs/module_name.logs"
    level: INFO
    formatter: detailed
loggers:
  "":
    handlers: [default]
    level: INFO
  module_name:
    handlers: [default, file_handler]
    level: INFO
    propagate: false

